### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by git900000** [gokdeniz66/BrowserBuddy#1]
I cannot open developer mode, as it is disabled by my administrator. Is there a different way to execute the program?

**Comment by gokdeniz66** [comment]
Unfortunately, it’s not possible to run the extension without developer mode enabled. The only alternative would be publishing it on the Chrome Web Store, but I don’t plan on doing that.

**Comment by git900000** [comment]
> Unfortunately, it’s not possible to run the extension without developer mode enabled. The only alternative would be publishing it on the Chrome Web Store, but I don’t plan on doing that.

Ok, thank you for the explanation. Additionally, I like your profile picture!

**Comment by gokdeniz66** [comment]
Thanks! I appreciate that you took the time to check out my project!

**Comment by git900000** [comment]
You're welcome! ;)

**Comment by git900000** [comment]
This may be weird, but would you like to join me and my friends SportsYou group? It's just where we can chat and such. If you wanna join, here's the link and code.

Code: 3NP4GAYX

Link: [Here!](https://www.sportsyou.com/teams/te-63511008-f65d-46ea-a1fa-924e2020ad90)

Sign up for SportsYou if you haven't already, and you would like to join.

See ya there! ;D

**Comment by gokdeniz66** [comment]
@git900000 Isn't that for sport related things? why not use discord?

**Comment by git900000** [comment]
Can't. Blocked.
________________________________

**Comment by git900000** [comment]
Update: New code.  Old code is now invalid. Code is: Y3A9-6486

**Comment by git900000** [comment]
Er... Sorry if I sound desperate, but would you like to join?
